### ISSUE TITLE
partially initialized module 'nobrainer' has no attribute 'io' (most likely due to a circular import)

### ISSUE THREAD

**Issue by wojtin** [neuronets/helpdesk#1]
### Bug description
```
partially initialized module 'nobrainer' has no attribute 'io' (most likely due to a circular import)
```

### How to reproduce
```
pip install nobrainer nilearn

import nobrainer
filepaths = nobrainer.io.read_csv("data.csv")
```
### Your personal set up
Windows 10, tested on python 3.1, 3.7, 3.9:

# paste output of `pip freeze` or `conda list` here
```
(nobrainer) C:\Users\samsung\Desktop\sLodz\_AI>python nobrainer.py
Traceback (most recent call last):
  File "C:\Users\samsung\Desktop\sLodz\_AI\nobrainer.py", line 1, in <module>
    import nobrainer
  File "C:\Users\samsung\Desktop\sLodz\_AI\nobrainer.py", line 2, in <module>
    filepaths = nobrainer.io.read_csv("data.csv")
AttributeError: partially initialized module 'nobrainer' has no attribute 'io' (most likely due to a circular import)

**Comment by kaczmarj** [comment]
@wojtin - i cannot reproduce this issue using `pip install nobrainer nilearn`, which installed nobrainer version 1.1.1.

can you please paste the outputs of `pip freeze` ? the version of nobrainer and other packages will be included.

**Comment by wojtin** [comment]
My fault, I have named my file nobrainer.py

Regards
